### ISSUE TITLE
Relative path

### ISSUE THREAD

**Issue by Hoi15A** [Immortalizd/botalizd#1]
`$!read("C:\Users\immor\AppData\Roaming\mIRC\scripts\ffz.btlzd")`
Now I'm not sure how this is in mIRC but, in regular programming, you want to use relative Paths.
For example it could look like this:
`$!read(".\scripts\ffz.btlzd")`

More info [HERE](https://en.wikipedia.org/wiki/Path_(computing)#Absolute_and_relative_paths)

**Comment by Immortalizd** [comment]
I'll try that. I tried using the % for appdata, i.e. %appdata% and it didn't work.

**Comment by Immortalizd** [comment]
it worked and is added.

**Comment by Hoi15A** [comment]
:+1:
